spring:
  application:
    name: demoEmployees

  datasource:
    url: jdbc:postgresql://localhost:5432/employees_management
    username: postgres
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update